version: 2
jobs:
  test:
    docker:
      - image: python:2
    steps:
      - checkout
      - run:
          name: Setup dependencies
          command: pip install -r requirements.txt
      - run:
          name: Testing
          command: python tests.py
      - store_test_results:
          path: build/test-results
      - persist_to_workspace:
          root: .
          paths:
            - .
workflows:
  version: 2
  main_flow:
    jobs:
      - test