version: 2
jobs:
  test:
    docker:
      - image: python:2
    steps:
      - checkout
      - run:
          name: Setup dependencies
          command: pip install -r requirements.txt
      - run:
          name: Testing
          command: python tests.py
      - persist_to_workspace:
          root: .
          paths:
            - .

  dockerize:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t $DOCKER_USER/ca-project:$CIRCLE_SHA1 -t $DOCKER_USER/ca-project:latest .
            docker push $DOCKER_USER/ca-project:$CIRCLE_SHA1
            docker push $DOCKER_USER/ca-project:latest
  deploy-testing:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to Testing
          command: |
              scp ./server.sh $SSH_USER@$SSH_HOST_TESTING:server.sh
              ssh $SSH_USER@$SSH_HOST_TESTING "export TARGET=testing; . server.sh $CIRCLE_SHA1"

  functional_test:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Functional testing
          command: |
              scp ./curl_test.sh $SSH_USER@$SSH_HOST_TESTING:curl_test.sh
              ssh $SSH_USER@$SSH_HOST_TESTING . curl_test.sh $SSH_HOST_TESTING

  package:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build release zip
          command: mkdir ./releases && zip -r ./releases/$CIRCLE_SHA1.zip ./
      - store_artifacts:
          path: ./releases/
          destination: releases/

  deploy-production:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to production
          command: |
              scp ./server.sh $SSH_USER@$SSH_HOST_PRODUCTION:server.sh
              ssh $SSH_USER@$SSH_HOST_PRODUCTION "export TARGET=production; . server.sh $CIRCLE_SHA1"

workflows:
  version: 2
  main_flow:
    jobs:
      - test
      - dockerize:
          filters:
            branches:
              only: master
          requires:
            - test
      - deploy-testing:
          requires:
            - dockerize
          filters:
            branches:
              only:
                - master
      - functional_test:
          requires:
            - deploy-testing
          filters:
            branches:
              only:
                - master
      - deploy-production:
          requires:
            - functional_test
          filters:
            branches:
              only: master
            tags:
              only: /v[0-9]+(\.[0-9]+)+(\.[0-9]+)/
      - package:
          requires:
            - functional_test
          filters:
            branches:
              only:
                - master
