version: 2
jobs:
  test:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt install python3-pip
      - run:
          name: Setup dependencies
          command: pip install -r requirements.txt
      - run:
          name: Testing
          command: python tests.py
      - persist_to_workspace:
          root: .
          paths:
            - .
  dockerize:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t $DOCKER_USER/ca-project:$CIRCLE_SHA1 -t $DOCKER_USER/ca-project:testing -t $DOCKER_USER/ca-project:production .
            docker push $DOCKER_USER/ca-project:testing
            docker push $DOCKER_USER/ca-project:production
  deploy-testing:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to Testing
          command: |
              scp ./server.sh $SSH_USER@$SSH_HOST_TESTING:server.sh
              ssh $SSH_USER@$SSH_HOST_TESTING "export TARGET=testing; . server.sh"
  deploy-production:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to production
          command: |
              scp ./server.sh $SSH_USER@$SSH_HOST_PRODUCTION:server.sh
              ssh $SSH_USER@$SSH_HOST_PRODUCTION "export TARGET=production; . server.sh"

  create-artifact:
    docker:
      - image: ubuntu:18.04
    steps:
      - attach_workspace:
          at: .
      - run: zip -r artifact.zip .
      - store_artifacts:
          path: .
          destination: prefix

workflows:
  version: 2
  main_flow:
    jobs:
      - test
      - dockerize:
          filters:
            branches:
              only: master
          requires:
            - test
      - deploy-testing:
          requires:
            - dockerize
          filters:
            branches:
              only:
                - master
      - create-artifact:
          requires:
            - test
      - deploy-production:
          type: approval
          requires:
            - dockerize
          filters:
            branches:
              only: master
            tags:
              only: /v[0-9]+(\.[0-9]+)+(\.[0-9]+)/
