version: 2
jobs:
  test:
    docker:
      - image: python:2
    steps:
      - checkout
      - run:
          name: Setup dependencies
          command: pip install -r requirements.txt
      - run:
          name: Testing
          command: python tests.py
      - store_test_results:
          path: build/test-results
      - persist_to_workspace:
          root: .
          paths:
            - .
  dockerize:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t $DOCKER_USER/ca-project:CIRCLE_SHA1 .
  deploy-testing:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to Testing
          command: |
              docker tag $DOCKER_USER/ca-project:CIRCLE_SHA1 $DOCKER_USER/ca-project:testing
              docker push $DOCKER_USER/ca-project:testing
              scp ./server.sh $SSH_USER@$SSH_HOST_TESTING:server.sh
              ssh $SSH_USER@$SSH_HOST_TESTING "./server.sh"
  deploy-production:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to production
          command: |
              echo "production"
              # docker tag $DOCKER_USER/ca-project:CIRCLE_SHA1 $DOCKER_USER/ca-project:testing
              # docker push $DOCKER_USER/ca-project:testing
              # scp ./server.sh $SSH_USER@$SSH_HOST_TESTING:server.sh
              # ssh $SSH_USER@$SSH_HOST_TESTING "./server.sh"
workflows:
  version: 2
  main_flow:
    jobs:
      - test
      - dockerize:
          requires:
            - test
      - deploy-testing:
          requires:
            - dockerize
          filters:
            branches:
              only:
                - master
      - deploy-production:
          requires:
            - dockerize
          filters:
            branches:
              only: add-production
            tags:
              only: /v[0-9]+(\.[0-9]+)+(\.[0-9]+)/
