version: 2
jobs:
  test:
    docker:
      - image: python:2
    steps:
      - checkout
      - run:
          name: Setup dependencies
          command: pip install -r requirements.txt
      - run:
          name: Testing
          command: python tests.py
      - store_test_results:
          path: test
      - persist_to_workspace:
          root: .
          paths:
            - .
  dockerize:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t $DOCKER_USER/ca-project:$CIRCLE_SHA1 -t $DOCKER_USER/ca-project:latest .
      - run: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker push $DOCKER_USER/ca-project:$CIRCLE_SHA1
              docker push $DOCKER_USER/ca-project:latest
            fi
  deploy-testing:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to Testing
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                scp ./server.sh $SSH_USER@$SSH_HOST:server.sh
                ssh $SSH_USER@$SSH_HOST ". server.sh"
              fi
workflows:
  version: 2
  main_flow:
    jobs:
      - test
      - dockerize:
          filters:
            branches:
              only: master
          requires:
            - test
      - deploy-testing:
          requires:
            - dockerize
