version: 2
jobs:
  test:
    docker:
      - image: python:2
    steps:
      - checkout
      - run:
          name: Setup dependencies
          command: pip install -r requirements.txt
      - run:
          name: Testing
          command: python tests.py
      - store_test_results:
          path: build/test-results
      - persist_to_workspace:
          root: .
          paths:
            - .
  dockerize:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t $DOCKER_USER/ca-project:CIRCLE_SHA1 .
  deploy-testing:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to Testing
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                docker tag $DOCKER_USER/ca-project:CIRCLE_SHA1 $DOCKER_USER/ca-project:testing
                docker push $DOCKER_USER/ca-project:testing
                scp ./server.sh $SSH_USER@$SSH_HOST_TESTING:server.sh
                ssh $SSH_USER@$SSH_HOST_TESTING "./server.sh"
              fi
  deploy-production:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to production
          command: |
              echo "production"
              # if [ "${CIRCLE_BRANCH}" == "master" ]; then
              #   scp ./server.sh $SSH_USER@$SSH_HOST_PRODUCTION:server.sh
              #   ssh $SSH_USER@$SSH_HOST_PRODUCTION "./server.sh"
              # fi
workflows:
  version: 2
  main_flow:
    jobs:
      - test
      - dockerize:
          requires:
            - test
      - deploy-testing:
          requires:
            - dockerize
      - deploy-production:
          requires:
            - dockerize
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)+(\.[0-9]+)/
