version: 2
jobs:
  test:
    docker:
      - image: python:2
    steps:
      - checkout
      - run:
          name: Setup dependencies
          command: pip install -r requirements.txt
      - run:
          name: Testing
          command: python tests.py
      - store_test_results:
          path: build/test-results
      - persist_to_workspace:
          root: .
          paths:
            - .
  dockerize:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t $DOCKER_USER/ca-project:$CIRCLE_SHA1 -t $DOCKER_USER/ca-project:latest .
      - run: docker push $DOCKER_USER/ca-project:$CIRCLE_SHA1
      - run: docker push $DOCKER_USER/ca-project:latest

workflows:
  version: 2
  main_flow:
    jobs:
      - test
      - dockerize:
          requires:
            - test